package egovernance;


import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Avtar Singh
 */
public class register_frame extends javax.swing.JFrame {
Connection conn1=null;
PreparedStatement pat1=null;
PreparedStatement pat2=null;
ResultSet rs1=null;
int pass;
    /**
     * Creates new form register_frame
     */
    public register_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agetxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        malerb = new javax.swing.JRadioButton();
        femalerb = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usernametxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        adhaartxt = new javax.swing.JTextField();
        adhaarlbl = new javax.swing.JLabel();
        usernamelbl = new javax.swing.JLabel();
        pwdtxt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(406, 364));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER  FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 54, 37, 15);

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        getContentPane().add(nametxt);
        nametxt.setBounds(87, 51, 87, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 82, 37, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 60, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sex");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 155, 37, 15);
        getContentPane().add(agetxt);
        agetxt.setBounds(87, 79, 87, 20);
        getContentPane().add(addresstxt);
        addresstxt.setBounds(87, 110, 190, 23);

        buttonGroup1.add(malerb);
        malerb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        malerb.setForeground(new java.awt.Color(255, 255, 255));
        malerb.setText("Male");
        malerb.setContentAreaFilled(false);
        getContentPane().add(malerb);
        malerb.setBounds(87, 151, 53, 23);

        buttonGroup1.add(femalerb);
        femalerb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        femalerb.setForeground(new java.awt.Color(255, 255, 255));
        femalerb.setText("Female");
        femalerb.setContentAreaFilled(false);
        femalerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalerbActionPerformed(evt);
            }
        });
        getContentPane().add(femalerb);
        femalerb.setBounds(170, 150, 100, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("login Details");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(125, 213, 75, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 241, 59, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 272, 59, 15);

        jButton1.setText("register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(91, 304, 69, 23);

        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernametxt);
        usernametxt.setBounds(87, 238, 124, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Adhaar id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 184, 59, 15);

        adhaartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adhaartxtActionPerformed(evt);
            }
        });
        getContentPane().add(adhaartxt);
        adhaartxt.setBounds(87, 181, 167, 20);
        getContentPane().add(adhaarlbl);
        adhaarlbl.setBounds(272, 181, 134, 20);
        getContentPane().add(usernamelbl);
        usernamelbl.setBounds(262, 238, 144, 20);
        getContentPane().add(pwdtxt);
        pwdtxt.setBounds(87, 269, 124, 20);

        jButton2.setText("Back to login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(193, 304, 103, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egovernanace_images/background-wallpapers-26.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -30, 410, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void femalerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalerbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalerbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String sex;
if(malerb.isSelected()){
sex="male";
}else{
sex="female";
} 
conn1=mysqlconnect.ConnectDB();
String sql="insert into userdetails values(?,?,?,?,?,?)";
String sql1="insert into login values(?,?,?)";
if (pass==1){
try{
pat1=conn1.prepareStatement(sql);
pat2=conn1.prepareStatement(sql1);
pat1.setString(1,usernametxt.getText());
pat1.setString(2,nametxt.getText());
pat1.setString(3,agetxt.getText());
pat1.setString(4,addresstxt.getText());
pat1.setString(5,sex);
pat1.setString(6,adhaartxt.getText());
pat2.setString(1,usernametxt.getText());
pat2.setString(2,pwdtxt.getText());
pat2.setString(3, "citizen");
pat2.executeUpdate();
pat1.executeUpdate();

}catch(Exception e){
JOptionPane.showMessageDialog(this, e);
}
}
else{
JOptionPane.showMessageDialog(null,"Please fill correct details");
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adhaartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adhaartxtActionPerformed
     conn1 = mysqlconnect.ConnectDB();
       String sql="Select * from gov_record where adhaar_id=?";
       try{
         pat1=conn1.prepareStatement(sql);
         pat1.setString(1,adhaartxt.getText());
         rs1=pat1.executeQuery();
         if (rs1.next()){
             pass=1;
             adhaarlbl.setText("Verified number");
         }
         else{
         pass=0;
         adhaarlbl.setText("Invalid Number");
         }
       }catch(SQLException e){
           JOptionPane.showMessageDialog(this, e);
       }// TODO add your handling code here:
    }//GEN-LAST:event_adhaartxtActionPerformed

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
      conn1 = mysqlconnect.ConnectDB();
       String sql="Select * from login where username=?";
       try{
         pat1=conn1.prepareStatement(sql);
         pat1.setString(1,usernametxt.getText());
         rs1=pat1.executeQuery();
         if (rs1.next()){
             pass=0;
             usernamelbl.setText("username already exist ");
         }
         else{
         pass=1;
         usernamelbl.setText("valid username");
         }
       }catch(SQLException e){
           JOptionPane.showMessageDialog(this, e);
       }
       // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
login l=new login();
l.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JLabel adhaarlbl;
    private javax.swing.JTextField adhaartxt;
    private javax.swing.JTextField agetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femalerb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton malerb;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField pwdtxt;
    private javax.swing.JLabel usernamelbl;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
