package egovernance;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;

import javax.swing.JOptionPane;
/**
 *
 * @author Avtar Singh
 */
public class vote_idea extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs =null;
ResultSet rs1=null;
ResultSet rs2=null;
PreparedStatement pat=null;
PreparedStatement pat2=null;
PreparedStatement pat3=null;
PreparedStatement pat4=null;
    /**
     * Creates new form vote_idea
     */
    public vote_idea() {
        initComponents();
        loginlbl.setText(user.username);
        conn=mysqlconnect.ConnectDB();
        String sql="select idea_subject from user_idea where pass=?";
        
        try{
            pat=conn.prepareStatement(sql);
            pat.setString(1,"yes");
            rs=pat.executeQuery();
            while(rs.next()){
            ideacb.addItem(rs.getString(1));
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ideacb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        yesrb = new javax.swing.JRadioButton();
        norb = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        desctxt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginlbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loginlbl.setText("User");
        getContentPane().add(loginlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 150, 18));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egovernanace_images/icons8-Hand Up-48.png"))); // NOI18N
        jLabel1.setText("VOTE IDEA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 40));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Give your valuable vote here");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 280, -1));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 720, 120));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        ideacb.setBackground(new java.awt.Color(153, 153, 255));
        ideacb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ideacbActionPerformed(evt);
            }
        });
        jPanel2.add(ideacb);
        ideacb.setBounds(140, 20, 380, 30);

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select to vote");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 220, 100, 20);

        buttonGroup1.add(yesrb);
        yesrb.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        yesrb.setForeground(new java.awt.Color(255, 255, 255));
        yesrb.setText("pass it");
        yesrb.setContentAreaFilled(false);
        jPanel2.add(yesrb);
        yesrb.setBounds(160, 220, 90, 25);

        buttonGroup1.add(norb);
        norb.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        norb.setForeground(new java.awt.Color(255, 255, 255));
        norb.setText("Don't Pass it");
        norb.setContentAreaFilled(false);
        norb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norbActionPerformed(evt);
            }
        });
        jPanel2.add(norb);
        norb.setBounds(320, 220, 120, 25);

        desctxt.setBackground(new java.awt.Color(153, 153, 255));
        desctxt.setColumns(20);
        desctxt.setRows(5);
        jScrollPane1.setViewportView(desctxt);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 70, 380, 120);

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select Subject");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 30, 99, 17);

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIPTION");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 96, 17);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 270, 720, 60);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 720, 330));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egovernanace_images/icons8-User-48.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Hey!");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String vote_value;
if(yesrb.isSelected()){
   vote_value="yes";
}
else{
vote_value="No";}
String sql="Select* from vote_details where username=? and idea_subject=?";  
    try {
        pat3=conn.prepareStatement(sql);
        pat3.setString(1,user.username);
        pat3.setString(2,(ideacb.getSelectedItem()).toString() );
        rs2=pat3.executeQuery();
        if (rs2.next()){
        JOptionPane.showMessageDialog(null, "You have already voted");
        }
        else{
        String sql2="insert into vote_details(username,idea_subject,vote_value,vote_date) "
                + "values(?,?,?,curdate())";
        pat4=conn.prepareStatement(sql2);
        pat4.setString(1,user.username);
        pat4.setString(2,(ideacb.getSelectedItem()).toString() );
        pat4.setString(3,vote_value);
        pat4.executeUpdate();
        JOptionPane.showMessageDialog(null, "Successfully Submitted");
        }
// TODO add your handling code here:
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ideacbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ideacbActionPerformed
String sql1="Select idea_description from user_idea where idea_subject=?";
try{
   pat2=conn.prepareStatement(sql1);
   pat2.setString(1,(ideacb.getSelectedItem()).toString());
   rs1=pat2.executeQuery();
   if(rs1.next()){
   desctxt.setText(rs1.getString(1));
   }
   
}catch(Exception e){
    JOptionPane.showMessageDialog(this, e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_ideacbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
citizen_home c=new citizen_home();
c.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void norbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_norbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ideacb.removeAllItems();
        loginlbl.setText(user.username);
        conn=mysqlconnect.ConnectDB();
        String sql="select idea_subject from user_idea where pass=?";
        
        try{
            pat=conn.prepareStatement(sql);
            pat.setString(1,"yes");
            rs=pat.executeQuery();
            while(rs.next()){
            ideacb.addItem(rs.getString(1));
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vote_idea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vote_idea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vote_idea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vote_idea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vote_idea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea desctxt;
    private javax.swing.JComboBox<String> ideacb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginlbl;
    private javax.swing.JRadioButton norb;
    private javax.swing.JRadioButton yesrb;
    // End of variables declaration//GEN-END:variables
}
